import Head from 'next/head'
import React from 'react'
import Container from '../components/Layout'

export default function about() {
  return (<>

    <Head>
      <title>My About page</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>about</div>

  </>
  )
}
