version: '3.9' #optional

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    restart: always

  server:
    image: server-node
    container_name: node-server
    ports:
      - 4000:4000
    environment:
      -  MONGO_URI=mongodb://mongo_db:27017/test
    depends_on:
      - mongo_db
    restart: always
