version: '3.9' #optional

services:
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    restart: always
  redis_db:
    image: redis
    container_name: redis_db
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
  server:
    image: server-node
    container_name: node-server
    ports:
      - 4000:4000
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/test
      - REDIS_HOST=redis_db
      - REDIS_PORT=6379
    depends_on:
      - mongo_db
      - redis_db
    restart: always
volumes:
  redis-data:
